### ISSUE TITLE
Generalize types within `cardano-coin-selection` library.

### ISSUE THREAD

**Issue by jonathanknowles** [input-output-hk/cardano-coin-selection#17]
# Context

The [`cardano-coin-selection`](https://github.com/input-output-hk/cardano-coin-selection) library currently duplicates some of the types that are defined within the [`cardano-wallet`](https://github.com/input-output-hk/cardano-wallet/) library.

It would be desirable to replace these duplicated types with abstract types or interfaces, allowing consumers of the library (including `cardano-wallet`) to use their own concrete types.

# Decision

Revise the types used in the [`cardano-coin-selection`](https://github.com/input-output-hk/cardano-coin-selection) library, replacing concrete types with abstract types (or interfaces) where it makes sense.

## Types to Generalize

- [x] [`Cardano.CoinSelection.CoinSelectionLimit`](https://github.com/input-output-hk/cardano-coin-selection/blob/0dfd846c68669d60fdff4f77dc8ae19ae25bf0e1/src/library/Cardano/CoinSelection.hs#L278)
     This was originally defined in terms of `Word8`. It has been widened to `Word16`.

- [x] `TxIn` (used in the inputs of a `CoinSelection`)
     Since coin selection algorithms are agnostic to the type of input identifier, this has been replaced with the type variable `i`.

- [x] `Address` (used in the outputs of a `CoinSelection`)
     Since coin selection algorithms are agnostic to the type of output identifier, this has been replaced with a type variable `o`.

- [x] `UTxO`
    This has been replaced with `CoinMap i`, where `i` refers to an input identifier type.

- [x] `[TxOut]`
    This has been replaced with `CoinMap o`, where `o` refers to an output identifier type.

- [x] `Hash`
    This has been removed, as it was part of `TxIn` which has also been removed.

- [x] `Coin`
     This was originally defined in terms of `Word64`, and has now been redefined in terms of `Natural`.

- [x] `Fee`
     This was originally defined in terms of `Word64`, and has now been redefined in terms of `Coin` (which is defined in terms of `Natural`).

- [x] `DustThreshold`
     This was originally defined in terms of `Word64`, and has now been redefined in terms of `Coin` (which is defined in terms of `Natural`).

**Comment by jonathanknowles** [comment]
@KtorZ Code review identified one type that could potentially be widened or generalized: https://github.com/input-output-hk/cardano-coin-selection/blob/0dfd846c68669d60fdff4f77dc8ae19ae25bf0e1/src/library/Cardano/CoinSelection.hs#L278-L283

I did experiment with widening this type, and was successfully able to widen it to `Word16` without issues (see https://github.com/input-output-hk/cardano-coin-selection/tree/jonathanknowles/widen-selection-limit).

However, widening it to `Word32` or `Word64` causes the test for `idealBatchSize` to run for an excessively long time (due to the way that `fixPoint` increments by `1` each iteration).

In your opinion, is it an issue that the the input limit is defined in terms of `Word8`?

**Comment by jonathanknowles** [comment]
Just for the record, we decided to widen the type of `CoinSelectionLimit` to `Word16`. See https://github.com/input-output-hk/cardano-coin-selection/issues/17#issuecomment-618161639.

**Comment by piotr-iohk** [comment]
lgtm.
