### ISSUE TITLE
Revise documentation for `cardano-coin-selection` library.

### ISSUE THREAD

**Issue by jonathanknowles** [input-output-hk/cardano-coin-selection#18]
# Context

As part of the work to create a separate [**coin selection and fee balancing library**](https://github.com/input-output-hk/cardano-wallet/milestone/58), we'd like the library to be documented in a way that's consistent with good practices used by other popular libraries in the Haskell ecosystem.

# Decision

Revise the public documentation for the [`cardano-coin-selection`](https://github.com/input-output-hk/cardano-coin-selection) library.

# Acceptance Criteria

## Source Code Documentation (Haddock)

- [x] Every public module _should_ have a clear summary to state its purpose.
- [x] Every exported function _should_ have a clear comment to illustrate its purpose. 
- [x] Every exported type _should_ have a clear comment to illustrate its purpose.
- [x] Every exported constructor _should_ have a clear comment to illustrate its purpose.

## Other Documentation

- [x] The [home page](https://github.com/input-output-hk/cardano-coin-selection) for the `cardano-coin-selection` library _must_ explain the basic purpose of the library. This page can delegate to source code documentation where appropriate, to avoid duplication.

# Development 

- [x] Remove Cardano-specific blockchain limitations from comments. For example:
    https://github.com/input-output-hk/cardano-coin-selection/blob/f62d069062f196d3b251ac6e7a039a0030d929d6/src/library/Cardano/CoinSelection/Migration.hs#L19-L21
- [x] State what is meant by `relatively-balanced` in function `idealBatchSize`. See [this comment](https://github.com/input-output-hk/cardano-coin-selection/pull/55#discussion_r413504278). (We eventually solved this by referring to `idealBatchSize` as an automatic way to generate a suitable batch size for `selectCoins`. See https://input-output-hk.github.io/cardano-coin-selection/haddock/cardano-coin-selection-1.0.0/Cardano-CoinSelection-Algorithm-Migration.html#v:selectCoins.)
- [x] Check for obvious grammar and spelling errors.

# QA 

_Section to be added._

**Comment by piotr-iohk** [comment]
@jonathanknowles  haddock doc (https://input-output-hk.github.io/cardano-coin-selection/haddock/) returns 404 for: 

Cardano.CoinSelection.Algorithm
Cardano.CoinSelection.Algorithm.LargestFirst
Cardano.CoinSelection.Algorithm.Migration
Cardano.CoinSelection.Algorithm.Random
Cardano.CoinSelection.Fee

**Comment by piotr-iohk** [comment]
Closing, the issue for haddock documentation -> https://github.com/input-output-hk/cardano-coin-selection/issues/60.
