### ISSUE TITLE
Revise public API of `cardano-coin-selection` library.

### ISSUE THREAD

**Issue by jonathanknowles** [input-output-hk/cardano-coin-selection#30]
# Context

As part of the work to create a separate [**coin selection and fee balancing library**](https://github.com/input-output-hk/cardano-wallet/milestone/58), we need to ensure that the public API and source code is consistent with best practices generally adopted by the Haskell community.

# Decision

Conduct an examination of the public API and source code, and revise it as necessary to bring it into line with best practices adopted within the Haskell community.

# Development

## Areas to revise

- [x] **Module structure**

    The migration algorithm, while designed to select coins, doesn't have the same type as other algorithms such as `Largest-First` or `Random-Improve`, despite sharing a common `Cardano.CoinSelection` parent module.

    The `Fee` module is also not a coin selection algorithm _per se_, so it should probably not be at the same level as the coin selection algorithms. 

    We decided to adopt the following module hierarchy:

    ```hs
    Cardano
    └── CoinSelection
        ├── Algorithm 
        │   ├── LargestFirst
        │   ├── Migration
        │   └── RandomImprove
        └── Fee
    ```  

- [x] **`Buildable` instances**

    These have been moved out of the public API, and restricted to just the test code.

- [x] **`CoinSelectionError` type**

    We have:
    - [x] Added record fields to disambiguate the constructor arguments.
    - [x] Used specific types for currency values, rather than `Word64`.
    - [x] Embedded more information in each error, where possible.<br><br>

    Fixed in #53.<br><br>

- [x] **`ErrAdjustForFee` type**

    We now:
    - [x] Use the `Fee` type, rather than `Word64`.<br><br>

- [x] **`CoinSelectionAlgorithm` fall-back/delegation**

    The `Random-Improve` algorithm no longer **_delegates_** to `Largest-First` if it fails to find a selection. (See https://github.com/input-output-hk/cardano-coin-selection/pull/44).

    If a library user wishes to implement fallback themselves, it's trivial to implement by calling one algorithm after the other.

    For `cardano-wallet`, it's important that existing fallback behaviour is preserved when we eventually consume the `cardano-coin-selection` from that library. This requirement has been captured on the acceptance criteria here: https://github.com/input-output-hk/cardano-coin-selection/issues/20

- [x] **`Types` module**

    This module has been merged into `CoinSelection`.

- [x] **`ShowFmt` type**

    This has been removed from the public API.

- [x] **`Dom` type**

    This has been removed from the public API.

- [x] **`excluding`, `isSubsetOf`, `restrictedBy`, `restrictedTo` functions**

    These have been removed from the public API.

- [x] **`distance` function**

    This has been removed from the public API.

- [x] **`invariant` function**

    This has been removed from the public API.

- [x] **`CoinSelection` type**

    Both `inputs` and `outputs` are now of type `CoinMap`.

- [x] **`HasCallStack` constraints**

    We should examine whether all of these are required, or only some, and remove those that are not necessary.

- [x] **`TODO` comments**

    There are no more TODO comments within library source code. (All issues have been addressed.) There are some TODO comments within the test code relating to reduction of code duplication, but these do not prevent publication of the library.

**Comment by jonathanknowles** [comment]
Comment from @KtorZ :

- I don't think any of the `excluding`, `isSubsetOf`, `restrictedBy`, `restrictedTo` is any useful to the coin-selection.
- Same goes for `Dom`, which was useful to make a parallel with the spec in the wallet model but very superfluous for the CS.
- `ShowFmt` is some internal stuff we used in the past and have stop used / started to remove everywhere we could.
- Even the `UTxO` type feels redundant here (and the coin selection algorithms keep on unwrapping and rewrapping things to `UTxO` so. it's not like it buys us really anything).
- invariant is in .Types for a mysterious reason

**Comment by jonathanknowles** [comment]
Hi @KtorZ 

Do you have an opinion on the question in the description relating to the `Migration` module?

It could be fine to leave it as is, though if we identify a **_better_** module layout, it'd be best to make the change before releasing rather than afterwards. :+1:

**Comment by KtorZ** [comment]
I do like keeping modules that are related under the same hierarchy. What I do find slightly disturbing in the current hierarchy is mainly that `Fee` is at the same level as the coin selection algorithms.

So, My suggestion would be to move from:

```
└── Cardano
    ├── CoinSelection
    │   ├── Fee.hs
    │   ├── LargestFirst.hs
    │   ├── Migration.hs
    │   └── RandomImprove.hs
    └── CoinSelection.hs
```

to

```
├── CoinSelection
│   └── Algorithm
│       ├── LargestFirst.hs
│       ├── Migration.hs
│       └── RandomImprove.hs
├── CoinSelection.hs
└── Fee.hs
```

**Comment by KtorZ** [comment]
Even though `Migration` doesn't share exactly the same abstraction as the other, it still is an algorithm for selecting coins.

**Comment by jonathanknowles** [comment]
> Even though `Migration` doesn't share exactly the same abstraction as the other, it still is an algorithm for selecting coins.

This seems like a sensible solution. :+1:

**Comment by piotr-iohk** [comment]
lgtm.
