### ISSUE TITLE
Minimum bound for `Coin` inconsistent with specification.

### ISSUE THREAD

**Issue by jonathanknowles** [input-output-hk/cardano-coin-selection#38]
The [specification](https://github.com/input-output-hk/cardano-coin-selection/pull/16/files#diff-f8a2c3e44e2d8bf1d848c3c112859487R211) states that:

> A _coin value_ is a **positive** integer value that represents a number of
[Lovelace](https://cardanodocs.com/cardano/monetary-policy/).

However, our Haskell source code has the following definition for `Coin`:
```hs
-- | A non-negative integer value that represents a number of Lovelace.       
--    
-- One Ada is equal to 1,000,000 Lovelace.    
--    
newtype Coin = Coin   
    { getCoin :: Word64 }     
    deriving stock (Eq, Generic, Ord) 
    deriving Show via (Quiet Coin)    
      
instance NFData Coin  
      
instance Bounded Coin where   
    minBound = Coin 0 
    maxBound = Coin 45000000000000000      

coinIsValid :: Coin -> Bool   
coinIsValid c = c >= minBound && c <= maxBound     
```
We should consider whether this inconsistency matters, and if necessary, revise the definition or the specification so that they agree with one another.

**Comment by jonathanknowles** [comment]
@KtorZ what's your opinion on this?

I'm of a mind to close this as "won't fix".

Although [the specification defines a coin as a **_positive_** value](https://github.com/input-output-hk/cardano-coin-selection/pull/16#discussion_r397877789) (i.e., a value > 0), the existing code base allows the construction of zero-valued coins (for practicality purposes).

Zero-valued coins are of course filtered out from `change` by both coin selection _and_ fee balancing algorithms, but they are allowed to exist in the input and output maps.

We **_could_** fix the code to prevent this, but I suspect it would not be worth the effort.

**Comment by KtorZ** [comment]
I'd be quite inconvenient to not have zero value for Coin. Plus, there's nothing wrong in practice with "0 Lovelace". I know there was even discussions within the ledger team on whether _negative transaction amount_ should be allowed. 

So here, I'd actually say that the specs is wrong and should be re-worded to "non-negative" :)

**Comment by jonathanknowles** [comment]
> I'd be quite inconvenient to not have zero value for Coin. Plus, there's nothing wrong in practice with "0 Lovelace". I know there was even discussions within the ledger team on whether _negative transaction amount_ should be allowed.
> 
> So here, I'd actually say that the specs is wrong and should be re-worded to "non-negative" :)

Thanks for confirming!

I've left a reminder on the spec [here](https://github.com/input-output-hk/cardano-coin-selection/pull/16/files#r413727143).

I'll close this issue.  :+1:

**Comment by jonathanknowles** [comment]
Closing, as the specification has now been updated.

See https://github.com/input-output-hk/cardano-coin-selection/pull/16/files#diff-f8a2c3e44e2d8bf1d848c3c112859487R260-R261
